### ISSUE TITLE
请问为什么选择农历后，年份还是以阳历方式显示的？

### ISSUE THREAD

**Issue by magnusguo** [LoquatZ/flutter_lunar_datetime_picker#2]
请问为什么选择农历后，年份还是以阳历方式显示的？ 例如今年是2024年，希望在切换到农历后，年份可以以 ”二〇二四年”显示 而非 “2024年”，写一个数字一一对应的列表即可 谢谢大神

**Comment by cofon** [comment]
三个星期过去了, 作者应该是没时间改了,  反正onConfirm里有time值, 自动动手丰衣足食吧

**Comment by LoquatZ** [comment]
@magnusguo @cofon 
已增加农历Tab，农历年选项：
`DatePicker.showDatePicker(
                context,
                lunarPicker: lunar,
                showTime: true,
                showLunarYear: true,
                dateInitTime: time == null
                    ? DateInitTime(
                        currentTime: DateTime.now(),
                        maxTime: DateTime(2026, 12, 12),
                        minTime: DateTime(1995, 2, 4))
                    : DateInitTime(
                        currentTime:
                            DateFormat("yyyy-MM-dd h:m").parse(time ?? ""),
                        maxTime: DateTime(2026, 12, 12),
                        minTime: DateTime(1995, 2, 4)),
                onConfirm: (time, lunar) {
                  debugPrint(time.toString());
                  setState(() {
                    this.time =
                        "${time.year}-${time.month}-${time.day} ${time.hour}:${time.minute}";
                    this.lunar = lunar;
                  });
                },
                onChanged: (time, lunar) {
                  debugPrint("change:${time.toString()}");
                },
              )
`

**Comment by magnusguo** [comment]
谢谢作者 作者太帅了！
